name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on:
      - self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t kcaj21/livegab .
      - name: publish image to docker hub
        run: docker push kcaj21/livegab:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull kcaj21/livegab:latest
      - name: delete old container
        run: docker rm -f livegab-container
      - name: run docker container
        run: docker run -d -p 8080:8080 --name livegab-container kcaj21/livegab
